"""ApiToken Model

Revision ID: 2cccbd20e8e8
Revises: 8f88f4ff283a
Create Date: 2020-11-10 20:56:04.895954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cccbd20e8e8'
down_revision = '8f88f4ff283a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.Text(), nullable=True),
    sa.Column('api_token_valid_till', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
