"""Developer Model

Revision ID: 8f88f4ff283a
Revises: 
Create Date: 2020-11-08 20:16:18.245108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f88f4ff283a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('login_otp', sa.String(length=255), nullable=True),
    sa.Column('login_otp_created_at', sa.DateTime(), nullable=True),
    sa.Column('login_otp_valid_till', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_otp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developers')
    # ### end Alembic commands ###
